name: hidratese
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  dartz: ^0.10.1
  string_validator: ^0.3.0
  kiwi: ^4.0.2
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  font_awesome_flutter: ^9.1.0
  flutter_staggered_animations: ^1.0.0
  badges: ^2.0.1
  flare_flutter: ^3.0.2
  google_fonts: ^2.3.1
  sleek_circular_slider: ^2.0.1
  confetti: ^0.6.0-nullsafety
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.8
  flutter_local_notifications: ^9.1.5
  rxdart: ^0.27.3
  logger: ^1.1.0
  workmanager: ^0.4.1
  flutter_ringtone_player: ^3.1.1
  either_dart: ^0.1.4
  flutter_time_picker_spinner: ^2.0.0
  awesome_notifications: ^0.6.21
  flutter_switch: ^0.3.2
  introduction_screen: ^3.0.2
  flutter_native_splash: ^2.1.6

dev_dependencies: 
  build_runner: ^2.1.10
  kiwi_generator: ^4.0.2
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/1024.png"

flutter: 
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/sounds/
  
  # fonts:
  #   - family: Quicksand
  #     fonts:
  #     - asset: fonts/Quicksand/Quicksand-VariableFont_wght.ttf



